version: 2.1
jobs:

#Building Job
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run lint

# Testing Job

  test:
    docker: 
    - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: npm i
      - run: npm run test
#Auditing Job

  analyze:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run: npm i
        - run: npm audit

      
workflows:
  
  welcome:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
      
